# Generated by Django 6.0.4 on 2026-04-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='ConsumeIT', max_length=120)),
                ('site_tagline', models.CharField(default='Scalable web development, SEO, and automation for modern brands.', max_length=255)),
                ('site_url', models.URLField(default='https://www.consumeit.in')),
                ('default_meta_title', models.CharField(default='ConsumeIT | Web Development, SEO, AI Automation & Marketing', max_length=255)),
                ('default_meta_description', models.TextField(default='ConsumeIT helps brands grow with modern websites, search visibility, automation, and performance-driven marketing.')),
                ('contact_email', models.EmailField(default='consumeit.services@gmail.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('x_handle', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('google_analytics_measurement_id', models.CharField(blank=True, max_length=50)),
                ('default_og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
