# Generated by Django 6.0.4 on 2026-04-09 17:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_title', models.CharField(default='Build a growth engine, not just another website.', max_length=255)),
                ('hero_subtitle', models.TextField(default='ConsumeIT turns static marketing sites into high-converting digital platforms with SEO, automation, and scalable content operations.')),
                ('primary_cta_text', models.CharField(default='Get in touch', max_length=50)),
                ('primary_cta_url', models.CharField(default='/contact/', max_length=255)),
                ('secondary_cta_text', models.CharField(default='Read the blog', max_length=50)),
                ('secondary_cta_url', models.CharField(default='/blog/', max_length=255)),
                ('intro_title', models.CharField(default='A dynamic foundation for growth', max_length=255)),
                ('intro_text', models.TextField(default='We modernize brochure-style websites into modular Django platforms with reusable templates, editable CMS pages, and a search-ready content layer.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('price_label', models.CharField(max_length=50)),
                ('billing_period', models.CharField(blank=True, max_length=50)),
                ('features', models.TextField(help_text='One feature per line.')),
                ('cta_text', models.CharField(default='Get started', max_length=50)),
                ('cta_url', models.CharField(default='/contact/', max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('avatar_alt', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
