# Generated by Django 6.0.4 on 2026-04-09 17:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('menu_title', models.CharField(blank=True, max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('template_key', models.CharField(choices=[('standard', 'Standard'), ('contact', 'Contact')], default='standard', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('featured_image_alt', models.CharField(blank=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/pages/')),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_navigation', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
